theme: jekyll-theme-cayman
google_analytics: "G-TVRS8DXNWR"
defaults:
  -
    scope:
      path: "dgp" # an empty string here means all files in the project
    values:
      title: "Dirección de Proyectos"
      description: "Curso DIM"
